wandb_version: 1

batch_size:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.0005
epochs:
  desc: null
  value: 250
_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.15.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684432010.097232
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 1
      - 3
      - 8
      - 16
      - 23
      4: 3.9.15
      5: 0.15.3
      8:
      - 1
      - 5
      10:
      - 9
